// Generated by CoffeeScript 2.5.1
(function() {
  var app, express, listener, superagent;

  express = require("express");

  app = express();

  superagent = require("superagent");

  app.set("json spaces", 2);

  app.get("/", function(req, res) {
    return res.json({
      hello: "world"
    });
  });

  app.get("/api", function(req, res) {
    return res.json({
      api: "this is api"
    });
  });

  app.get("/api/brainly", async function(req, res) {
    var data;
    if (!req.query.q) {
      res.json({
        err: "empty query"
      });
    }
    data = (await superagent.get(`https://brainlya.hanifdwyputra.xyz/?q=${req.query.q}`));
    return res.json(data.body);
  });

  app.get("/api/instagram", async function(req, res) {
    var data;
    if (!req.query.username) {
      res.json({
        invalid: "username query"
      });
    }
    data = (await superagent.get(`https://instagram.hanifdwyputra.xyz/?username=${req.query.username}`));
    return res.json(data.body);
  });

  listener = app.listen(8080, function() {
    return console.log("Express running on %d", listener.address().port);
  });

}).call(this);
